# SPDX-FileCopyrightText: 2020 Álvaro Cebrián Juan <acebrianjuan@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on: [push, pull_request]

jobs:

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends ninja-build cmake qtbase5-dev qtpositioning5-dev
    - name: configure
      run: cd build && cmake -GNinja ..
    - name: build
      run: cd build && ninja
      
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: brew install ninja cmake qt
    - name: configure
      run: cd build && cmake -GNinja -DQt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5 .. 
    - name: build
      run: cd build && ninja

  REUSE-compliance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check REUSE compliance
      uses: docker://fsfe/reuse
      with:
        args: lint

