# SPDX-FileCopyrightText: 2020 Álvaro Cebrián Juan <acebrianjuan@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on: [push, pull_request]

jobs:

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends ninja-build cmake qtbase5-dev qtpositioning5-dev
    - name: configure
      run: cd build && cmake -GNinja ..
    - name: build
      run: cd build && ninja
    - name: check
      run: cd build && ctest --output-on-failure
     
      
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: brew install ninja cmake qt
    - name: configure
      run: cd build && cmake -GNinja -DQt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5 .. 
    - name: build
      run: cd build && ninja
    - name: check
      run: cd build && ctest --output-on-failure


  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends clang-format
    - name: run clang-format
      run: find . -iname \*.h -o -iname \*.c -o -iname \*.cpp | xargs clang-format -style=file -i
    - name: check
      run: git diff > clang_format.patch && echo -e "if \n [ -s clang_format.patch ] \nthen \n echo "clang-format not applied:"; echo ""; more clang_format.patch; exit 1 \nfi \n" > detect && chmod +x ./detect && ./detect


  cmakelint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install cmakelint
      - name: check CMake scripts
        run: find . -iname "CMakeLists.txt" -o -iname "*.cmake" | xargs cmakelint --filter=-linelength,-readability/wonkycase


  REUSE-compliance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check REUSE compliance
      uses: docker://fsfe/reuse
      with:
        args: lint

